version: '2'

services:
  app-web-profile:
    image: app-web-profile
    environment:
      - PUBLIC_HOST=25.85.82.83:8080
      - AUTH0_DOMAIN=app-profile.auth0.com
      - AUTH0_CLIENT_ID=lUnF8NKF9FBehcR3YcAxe4z0HQo3C2z3
      - CALLBACK=callback
      - SCOPE=openid profile email
      - API_DOMAIN=25.85.82.83
      - API_PORT=8081
      - API_VERSION=v1
    ports:
      - 8080:8080